/* ─── Simple syntax highlighting for code preview ─── */

const COMMON_KW = [
  "const",
  "let",
  "var",
  "function",
  "return",
  "if",
  "else",
  "for",
  "while",
  "class",
  "import",
  "export",
  "from",
  "async",
  "await",
  "new",
  "this",
  "try",
  "catch",
  "throw",
  "typeof",
  "switch",
  "case",
  "default",
  "break",
  "continue",
  "yield",
  "null",
  "undefined",
  "true",
  "false",
];

const LANG_KEYWORDS: Record<string, string[]> = {
  js: COMMON_KW,
  ts: [
    ...COMMON_KW,
    "type",
    "interface",
    "enum",
    "implements",
    "extends",
    "readonly",
    "private",
    "public",
    "protected",
    "abstract",
    "declare",
    "namespace",
    "module",
    "as",
    "keyof",
    "infer",
    "never",
    "unknown",
    "any",
    "void",
    "string",
    "number",
    "boolean",
    "bigint",
    "symbol",
    "object",
  ],
  py: [
    "def",
    "class",
    "return",
    "if",
    "elif",
    "else",
    "for",
    "while",
    "import",
    "from",
    "as",
    "try",
    "except",
    "finally",
    "raise",
    "with",
    "yield",
    "lambda",
    "pass",
    "break",
    "continue",
    "and",
    "or",
    "not",
    "in",
    "is",
    "True",
    "False",
    "None",
    "self",
    "global",
    "nonlocal",
    "async",
    "await",
    "print",
  ],
  rs: [
    "fn",
    "let",
    "mut",
    "const",
    "struct",
    "enum",
    "impl",
    "trait",
    "pub",
    "use",
    "mod",
    "match",
    "if",
    "else",
    "for",
    "while",
    "loop",
    "return",
    "break",
    "continue",
    "where",
    "type",
    "self",
    "Self",
    "super",
    "crate",
    "async",
    "await",
    "move",
    "dyn",
    "Box",
    "Vec",
    "String",
    "Option",
    "Result",
    "Some",
    "None",
    "Ok",
    "Err",
    "true",
    "false",
  ],
  go: [
    "func",
    "var",
    "const",
    "type",
    "struct",
    "interface",
    "package",
    "import",
    "return",
    "if",
    "else",
    "for",
    "range",
    "switch",
    "case",
    "default",
    "break",
    "continue",
    "go",
    "defer",
    "select",
    "chan",
    "map",
    "make",
    "new",
    "len",
    "cap",
    "append",
    "true",
    "false",
    "nil",
  ],
  css: [
    "@import",
    "@media",
    "@keyframes",
    "@font-face",
    "@charset",
    "@supports",
    "@layer",
    "!important",
    "var",
    "calc",
    "rgb",
    "rgba",
    "hsl",
    "hsla",
  ],
  html: [
    "<!DOCTYPE",
    "<html",
    "<head",
    "<body",
    "<div",
    "<span",
    "<script",
    "<style",
    "<link",
    "<meta",
    "<title",
    "<header",
    "<footer",
    "<main",
    "<section",
    "<nav",
    "<form",
    "<input",
    "<button",
  ],
  json: [],
  sql: [
    "SELECT",
    "FROM",
    "WHERE",
    "INSERT",
    "UPDATE",
    "DELETE",
    "CREATE",
    "DROP",
    "ALTER",
    "TABLE",
    "INTO",
    "VALUES",
    "SET",
    "JOIN",
    "LEFT",
    "RIGHT",
    "INNER",
    "OUTER",
    "ON",
    "AND",
    "OR",
    "NOT",
    "IN",
    "IS",
    "NULL",
    "ORDER",
    "BY",
    "GROUP",
    "HAVING",
    "LIMIT",
    "OFFSET",
    "UNION",
    "AS",
    "DISTINCT",
    "COUNT",
    "SUM",
    "AVG",
    "MIN",
    "MAX",
    "LIKE",
    "BETWEEN",
    "EXISTS",
    "INDEX",
    "PRIMARY",
    "KEY",
    "FOREIGN",
    "REFERENCES",
    "CONSTRAINT",
    "DEFAULT",
    "CHECK",
    "UNIQUE",
    "CASCADE",
  ],
};

const EXT_TO_LANG: Record<string, string> = {
  ts: "ts",
  tsx: "ts",
  js: "js",
  jsx: "js",
  mjs: "js",
  cjs: "js",
  py: "py",
  pyw: "py",
  pyi: "py",
  rs: "rs",
  go: "go",
  css: "css",
  scss: "css",
  sass: "css",
  less: "css",
  html: "html",
  htm: "html",
  sql: "sql",
};

export function highlightCode(text: string, ext: string): string {
  const lang = EXT_TO_LANG[ext.toLowerCase()];
  const keywords = lang ? (LANG_KEYWORDS[lang] ?? []) : [];

  let html = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // strings → comments → numbers → keywords
  html = html.replace(
    /(["'`])(?:(?!\1|\\).|\\.)*?\1/g,
    '<span class="preview-str">$&</span>',
  );
  html = html.replace(
    /(\/\/.*$|#.*$)/gm,
    '<span class="preview-comment">$&</span>',
  );
  html = html.replace(
    /\b(\d+\.?\d*)\b/g,
    '<span class="preview-num">$&</span>',
  );

  if (keywords.length) {
    const re = new RegExp(`\\b(${keywords.join("|")})\\b`, "g");
    html = html.replace(re, '<span class="preview-kw">$&</span>');
  }

  return html;
}
